# 仅仅@EnableEurekaClient是不够的，还需要在配置文件中注明自己的服务注册中心的地址，application.yml配置文件如下：

server:
  port: 8763

spring:
  application:
    name: ch-2-eureka-client    # 需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    # 需要在配置文件中注明自己的服务注册中心的地址